---
- name: Install docker
  aur:
    name:
      - docker
      - docker-compose
      - lazydocker
  become: yes
  become_user: aur_builder

- name: Enable the docker service
  ansible.builtin.service:
    name: docker
    enabled: true
  become: yes

- name: Check if docker group exists
  become: yes
  command: getent group docker
  register: docker_group_check
  ignore_errors: true

- name: Create docker group if it doesn't exist
  become: yes
  group:
    name: docker
    state: present
  when: docker_group_check.rc != 0

- name: Add current user to docker group
  become: yes
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: true
  when: docker_group_check.rc != 0

