--- 
- name: Check if dotfiles repo exists
  ansible.builtin.stat: 
    path: "~/dotfiles/.git"
  register: dotfiles_repo_status


- name: Install or update dotfiles
  when: not dotfiles_repo_status.stat.exists
  block:
    - name: Clone dotfiles 
      git:
        repo: 'https://github.com/eblakem/dotfiles.git'
        dest: ~/dotfiles
        clone: yes 
        update: yes

    - name: Stow adopt 
      ansible.builtin.command: ./stow-adopt.sh 
      args:
        chdir: ~/dotfiles
