---
- name: Firewall enable
  become: yes
  command: ufw enable

- name: Firewall disable incoming connections
  become: yes
  command: ufw default deny incoming

- name: Firewall enable cups
  become: yes
  command: ufw allow 631/tcp



