---
- name: Firewall enable
  community.general.ufw:
    state: enabled
  become: yes

- name: Firewall default deny incoming
  community.general.ufw:
    default: deny
    direction: incoming
  become: yes

- name: Firewall allow cups
  community.general.ufw:
    rule: allow
    port: '631'
    proto: tcp
  become: yes

- name: Firewall allow Forgejo UI and Registry
  community.general.ufw:
    rule: allow
    port: '3000'
    proto: tcp
  become: yes

- name: Firewall allow Forgejo SSH
  community.general.ufw:
    rule: allow
    port: '2222'
    proto: tcp
  become: yes
