--- 
- name: Check if fnm exists
  command: which fnm
  register: fnm_check
  ignore_errors: true

- name: Install fnm
  when: fnm_check.rc == 1
  block:
    - name: Run the fnm install script
      command: ../scripts/fnm-install.sh

    - name: Source fnm
      command: source ~/.config/fish/conf.d/fnm.fish

    - name: Install latest node
      command: fnm install --latest
  
