---
- name: Check if ghcup exists
  command: which ghcup
  register: ghcup_check
  ignore_errors: true
  failed_when: false

- name: Install ghcup if it doesn't exist 
  when: ghcup_check.rc == 1
  block:
    - name: Download ghcup
      get_url:
        url: https://get-ghcup.haskell.org
        dest: /tmp/ghcup
        mode: 0755

    - name: Install ghcup
      command: /tmp/ghcup 
      environment:
        - BOOTSTRAP_HASKELL_NONINTERACTIVE: 1

    - name: Cleanup ghcup
      command: rm -r /tmp/ghcup

- name: Update stack config to install-ghc false
  command: stack config set install-ghc false --global

- name: Update stack config to use system ghc
  command: stack config set system-ghc true --global


- name: Add .local/bin to path in .profile
  ansible.builtin.lineinfile:
    path: ~/.profile
    line: 'export PATH="home/$USER/.local/bin/:$PATH"'
    state: "present"

