---
# Update/Upgrade system
- import_tasks: tasks/upgrade.yml

# Install essential packages
- import_tasks: tasks/essential-packages.yml

# Setup aur builder user
- import_tasks: tasks/aur-builder.yml

# Create profile
- import_tasks: tasks/profile.yml

# Install yay
- import_tasks: tasks/yay.yml

# Clone dotfiles
- import_tasks: tasks/dotfiles.yml

# Install core packages
- import_tasks: tasks/core-packages.yml

# Install window manager 
- import_tasks: tasks/user-interface-packages.yml

# Install greeter
- import_tasks: tasks/greeter.yml

# Install bluetooth
- import_tasks: tasks/bluetooth.yml

# Install work packages
- import_tasks: tasks/work-packages.yml
  tags:
    - work

# Setup docker group
- import_tasks: tasks/docker-group.yml

# Setup devpod
- import_tasks: tasks/devpod.yml

# Setup ghcup
- import_tasks: tasks/ghcup.yml

# Setup firewall
- import_tasks: tasks/firewall.yml


