---
# Update/Upgrade system
- import_tasks: tasks/upgrade.yml

# Install essential packages
- import_tasks: tasks/essential-packages.yml

# Setup aur builder user
- import_tasks: tasks/aur-builder.yml

# Create profile
- import_tasks: tasks/profile.yml

# Update profile
- import_tasks: tasks/update-profile.yml

# Install yay
- import_tasks: tasks/yay.yml

# Clone dotfiles
- import_tasks: tasks/dotfiles.yml

# Configure portals
- import_tasks: tasks/portals-config.yml

# Install core packages
- import_tasks: tasks/core-packages.yml

# Install window manager 
- import_tasks: tasks/user-interface-packages.yml

# Install greeter
- import_tasks: tasks/greeter.yml

# Install bluetooth
- import_tasks: tasks/bluetooth.yml

# Install work packages
- import_tasks: tasks/work-packages.yml
  tags:
    - work

# Setup podman
- import_tasks: tasks/podman.yml

# Setup MSSQL Quadlet
- import_tasks: tasks/podman-mssql.yml

# Setup Forgejo Quadlet
- import_tasks: tasks/forgejo.yml

# Setup ghcup
- import_tasks: tasks/ghcup.yml
  tags:
    - home

# Setup mise 
- import_tasks: tasks/mise.yml

# Setup firewall
- import_tasks: tasks/firewall.yml

# Set default apps
- import_tasks: tasks/default-apps.yml

# Install power control
- import_tasks: tasks/tlp.yml
