--- 
- name: Install mise 
  become: yes
  become_user: aur_builder
  aur:
    name:
      - mise
    state: present

- name: Create fish completions directory
  ansible.builtin.file:
    path: ~/.config/fish/completions
    state: directory
    mode: '0755'

- name: Source mise in fish config
  ansible.builtin.lineinfile:
    path: ~/.config/fish/config.fish
    line: '/usr/bin/mise activate fish | source'
    create: yes
    state: present

- name: Install mise auto-completion 
  ansible.builtin.shell: 
    cmd: mise completion fish > ~/.config/fish/completions/mise.fish
    creates: ~/.config/fish/completions/mise.fish
