---
- name: Install podman
  aur:
    name:
      - podman
      - podman-docker
      - podman-compose
      - lazydocker
    state: present
  become: yes
  become_user: aur_builder

- name: Setup subuid/subgid for rootless podman
  block:
    - name: Ensure subuid exists for current user
      ansible.builtin.lineinfile:
        path: /etc/subuid
        line: "{{ lookup('env', 'USER') }}:100000:65536"
        regexp: "^{{ lookup('env', 'USER') }}:"
        create: yes
        state: present
      become: yes

    - name: Ensure subgid exists for current user
      ansible.builtin.lineinfile:
        path: /etc/subgid
        line: "{{ lookup('env', 'USER') }}:100000:65536"
        regexp: "^{{ lookup('env', 'USER') }}:"
        create: yes
        state: present
      become: yes
