---
- name: Check if .profile file exists
  ansible.builtin.stat:
    path: ~/.bash_profilele 
  register: profile_file

- name: Create .profile file
  ansible.builtin.file:
    path: ~/.profile
    state: touch 
  when: not profile_file.stat.exists

- name: Add environment variables to .profile
  ansible.builtin.lineinfile:
    path: ~/.profile
    regexp: '^export {{ item }}=*'
    line: "export {{ item }}=todo"
  loop:
    - GEMAPI

