---
- name: Check if .profile file exists
  ansible.builtin.stat:
    path: ~/.profile 
  register: profile_file

- name: Create .profile file
  ansible.builtin.file:
    path: ~/.profile
    state: touch 
  when: not profile_file.stat.exists


