---
- name: Check if environment variable exists
  command: grep -q "export {{ item }}" ~/.profile
  register: grep_result
  ignore_errors: yes

- name: Add environment variables to .profile
  ansible.builtin.lineinfile:
    path: ~/.profile
    line: "export {{ item }}=todo"
    state: "present"

