---
- name: Install user-interface packages  
  become: yes
  become_user: aur_builder
  aur:
    name: 
      - niri
      - fuzzel
      - mako
      - waybar
      - nwg-bar
      - nwg-look
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-gnome
      - gnome-keyring
      - swaybg
      - swayidle
      - swaylock
      - xwayland-satellite
      - polkit-gnome
      - adapta-gtk-theme
    state: present
