---
- name: Check if yay is installed
  ansible.builtin.stat:
    path: /usr/bin/yay 
  register: yay_check


- name: Cloning Yay
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: /tmp/yay
    clone: yes
    update: yes
  when: not yay_check.stat.exists

- name: Installing Yay
  makepkg:
    name: /tmp/yay
    state: present
  when: not yay_check.stat.exists

- name: Cleanup
  ansible.builtin.file:
    path: /tmp/yay
    state: absent
