---
- name: Setup Arch Linux
  hosts: local
  gather_facts: true
  roles:
    - 10_common
    - 20_packages
    - 30_config
    - 40_dotfiles
    - 50_desktop
    - 60_setup
    - 70_software
    - 99_cleanup

