--- 
- name: Install common system packages
  pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ system_packages }}"
  tags:
    - install_packages

- name: Check if yay is installed
  ansible.builtin.stat:
    path: /usr/bin/yay 
  register: yay_check

- name: Install yay if not present
  when: not yay_check.stat.exists and 'yay' in aur_packages
  block:
    - name: Clone yay 
      git:
        repo: 'https://aur.archlinux.org/yay.git'
        dest: /tmp/yay'
        clone: yes 
        update: yes

    - name: Build and install yay
      ansible.builtin.command: makepkg -si --noconfirm
      args:
        chdir: '/tmp/yay'
      changed_when: true # assume makepkg will change something

- name: Install AUR packages
  when: yay_check.stat.exists and aur_packages | length > 0
  command: yay -S --needed --noconfirm {{ item }} 
  loop: "{{ aur_packages | reject('equalto', 'yay') | list }}" # Exclude yay
  register: yay_result
  changed_when: "' there is nothing to do' not in yay_result.stdout"
  failed_when: "'error:' in yay_result.stdout"
  tags:
    - install_packages


- name: Install home system packages
  pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ home_packages }}"
  tags:
    - home
