--- 
- name: Check if dots repo exists
  ansible.builtin.stat: 
    path: "~/dots/.git"
  register: dotfiles_repo_status


- name: Install or update dotfiles
  when: dotfiles_repo_status.rc == 1
  block:
    - name: Clone dotfiles 
      git:
        repo: 'git@github.com:eblakem/dots.git'
        dest: ~/dots
        clone: yes 

    - name: Stow adopt 
      ansible.builtin.command: ./stow-adopt.sh 
      args:
        chdir: ~/dots
