---
- name: Update the system
  become: yes
  pacman:
    update_cache: yes
    upgrade: yes
  changed_when: false

- name: Install essential packages
  become: yes
  pacman:
    name:
      - base-devel
      - git 
      - openssh
      - yay
      - ansible-core
    state: present


